# Generated by Django 5.1.3 on 2024-11-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('animal', models.CharField(choices=[('D', 'Dolphin'), ('S', 'Shrimp'), ('C', 'Clownfish'), ('S', 'Starfish'), ('W', 'Whale')], max_length=1)),
                ('description', models.TextField(max_length=250)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
