# Generated by Django 5.1.3 on 2024-11-14 04:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spotting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='When spotted')),
                ('marine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.marine')),
            ],
        ),
    ]
